DROP TABLE IF EXISTS room_extra;
DROP TABLE IF EXISTS booking;
DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS extra;

CREATE TABLE extra (
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  icon VARCHAR(100) NOT NULL
);

CREATE TABLE room (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title            VARCHAR(255)  NOT NULL,
  description      VARCHAR(4000) NOT NULL,
  image_url        VARCHAR(512)  NOT NULL,
  price_per_night  DECIMAL(10,2) NOT NULL
);

CREATE TABLE room_extra (
  room_id  BIGINT NOT NULL REFERENCES room(id)  ON DELETE CASCADE,
  extra_id BIGINT NOT NULL REFERENCES extra(id) ON DELETE CASCADE,
  PRIMARY KEY (room_id, extra_id)
);

CREATE TABLE booking (
  id          VARCHAR(36)   PRIMARY KEY,
  room_id     BIGINT        NOT NULL REFERENCES room(id),
  first_name  VARCHAR(100)  NOT NULL,
  last_name   VARCHAR(100)  NOT NULL,
  email       VARCHAR(255)  NOT NULL,
  breakfast   BOOLEAN       NOT NULL DEFAULT FALSE,
  check_in    DATE          NOT NULL,
  check_out   DATE          NOT NULL,
  total_price DECIMAL(10,2) NOT NULL,
  status      VARCHAR(20)   NOT NULL DEFAULT 'CONFIRMED',
  created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_checkout CHECK (check_out >= check_in),
  CONSTRAINT chk_status   CHECK (status IN ('CONFIRMED', 'CANCELLED'))
);

CREATE INDEX idx_booking_room_id ON booking(room_id);
CREATE INDEX idx_booking_dates   ON booking(check_in, check_out);
CREATE INDEX idx_booking_email   ON booking(email);
CREATE INDEX idx_booking_status  ON booking(status);
