spring.application.name=hotel

spring.datasource.url=jdbc:sqlite:hotel.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.properties.hibernate.hbm2ddl.auto=none
spring.sql.init.mode=never
