spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/hotel_booking?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:hotel}
spring.datasource.password=${DB_PASSWORD:hotel}
spring.jpa.properties.hibernate.hbm2ddl.auto=none
spring.sql.init.mode=never

springdoc.api-docs.path=/api-docs
